from yacs.config import CfgNode


_C = CfgNode()

_C.VISUALISE_FREQUENCY = 100

# Train
_C.TRAIN = CfgNode()
_C.TRAIN.NUM_EPOCHS = 25
_C.TRAIN.BATCH_SIZE = 2
_C.TRAIN.LR = 5e-5
_C.TRAIN.EPOCHS_PER_SAVE = 3
_C.TRAIN.PIN_MEMORY = True
_C.TRAIN.NUM_WORKERS = 12
_C.TRAIN.LR_SCHEDULER = 'cosine'
_C.TRAIN.WARMUP_EPOCHS = 2

# Model
_C.MODEL = CfgNode()
_C.MODEL.BODY_MODEL = 'smplx'
_C.MODEL.SKINNING_WEIGHTS = True
_C.MODEL.POSE_BLENDSHAPES = True 
_C.MODEL.CANONICAL_STAGE_SIZE = 'base'
_C.MODEL.PBS_STAGE_SIZE = 'base'
_C.MODEL.USE_SAPIENS = True 

# Loss
_C.LOSS = CfgNode()
# _C.LOSS.VC_PM_LOSS_WEIGHT = 5.
# _C.LOSS.VC_CHAMFER_LOSS_WEIGHT = 5.
# _C.LOSS.VP_INIT_CHAMFER_LOSS_WEIGHT = 5.
# _C.LOSS.VP_CHAMFER_LOSS_WEIGHT = 5.
# _C.LOSS.W_REGULARISER_WEIGHT = 5.
_C.LOSS.VC_PM_LOSS_WEIGHT = 1.
_C.LOSS.VC_CHAMFER_LOSS_WEIGHT = 1.
_C.LOSS.VP_INIT_CHAMFER_LOSS_WEIGHT = 0.5
_C.LOSS.VP_CHAMFER_LOSS_WEIGHT = 10000.
_C.LOSS.W_REGULARISER_WEIGHT = 1.

_C.LOSS.DVC_LOSS_WEIGHT = 0.
_C.LOSS.ALPHA = 0.2
_C.LOSS.CONFIDENCE_THRESHOLD = 15.


# Input Data
_C.DATA = CfgNode()
_C.DATA.IMAGE_SIZE = 224 # 518 
_C.DATA.NORMALISE = True
_C.DATA.DIST_STD = 0.15 # 0.2
_C.DATA.ELEV_STD = 5 # 10
_C.DATA.AT_STD = 0.05
_C.DATA.DIST_OFFSET = 2.25
_C.DATA.ELEV_OFFSET = 10
_C.DATA.AT_OFFSET = -0.2
_C.DATA.LENGHTHEN_THUMAN = 40
_C.DATA.LENGHTHEN_D4DRESS = 800
_C.DATA.D4DRESS_PROBABILITY = 0.5


_C.SPEEDUP = CfgNode()
_C.SPEEDUP.MIXED_PRECISION = "16-mixed"
_C.SPEEDUP.ACCELERATOR = "gpu"
_C.SPEEDUP.MATMUL_PRECISION = "high"
_C.SPEEDUP.COMPILE = False

def get_cch_cfg_defaults():
    return _C.clone()